### PR TITLE
Updated sdk

### PR DESCRIPTION
**Pull request by srivastavarahull**
Updated viewer  with the new sdk version

### CODE REVIEW

**Comment by petrbroz** [comment]
Why are we bundling the SDKs in the codebase instead of installing them from NPM?

Please note that the develop branch is referred to by https://tutorials.autodesk.io, so any changes here would have to be reflected in the tutorial as well, and I don't think the tutorial should be asking people to embed the SDKs this way.

**Comment by sajith-subramanian** [comment]
@petrbroz -  We are yet to release the updated packages to npm. This pr is for first review & feedback to confirm all looks good. Once done, we will proceed to publish the updated packages and update this pr and remove local references.

**Comment by petrbroz** [comment]
Thanks for the clarification Sajith. Again, since this code is just for an internal review, there's no need to create a PR for the develop branch. Feel free to just create a test branch (either here or in your own fork), and share it with anyone who should review the code.

**Comment by sajith-subramanian** [comment]
Sure, thanks Petr. Will create test branch for future updates.

**Comment by fc88804DOTcn** [comment]
Oops！I had always assumed that the validity period of my account in the Aps Viewer module had expired, and I've been trying various other way to address the issue of converting files for web use. It's been quite a frustrating journey, but today, as I was reorganizing my code, I decided to give the old code one last shot,I  realized that it wasn't my account that was restricted, but rather the SDK that had been upgraded. Now I need to retest everything based on the new version.

**Comment by fc88804DOTcn** [comment]
Yes,  @petrbroz, you're right. We should use the new version by installing the npm package. This time, I'll first refer to the code provided by Mr. srivastavarahull. By the way, I found several tutorials on the official website not very user-friendly. I tried the step-by-step approach and the native Html+JS route, following the tutorials step by step, but both failed at the svf conversion step, always ending in failure. Fortunately, I later discovered this repository, and it worked on the first try. Thanks to the repository author and also to Mr. @srivastavarahull for his personal insights on the new version.

**Comment by petrbroz** [comment]
Closing. The code has already been updated to the latest beta version of the SDKs.

**Pull request closed without merging**
